/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsememoRouteImport } from './routes/usememo'
import { Route as SpinnerRouteImport } from './routes/spinner'
import { Route as IndexRouteImport } from './routes/index'

const UsememoRoute = UsememoRouteImport.update({
  id: '/usememo',
  path: '/usememo',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinnerRoute = SpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spinner': typeof SpinnerRoute
  '/usememo': typeof UsememoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spinner': typeof SpinnerRoute
  '/usememo': typeof UsememoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spinner': typeof SpinnerRoute
  '/usememo': typeof UsememoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spinner' | '/usememo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spinner' | '/usememo'
  id: '__root__' | '/' | '/spinner' | '/usememo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpinnerRoute: typeof SpinnerRoute
  UsememoRoute: typeof UsememoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usememo': {
      id: '/usememo'
      path: '/usememo'
      fullPath: '/usememo'
      preLoaderRoute: typeof UsememoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spinner': {
      id: '/spinner'
      path: '/spinner'
      fullPath: '/spinner'
      preLoaderRoute: typeof SpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpinnerRoute: SpinnerRoute,
  UsememoRoute: UsememoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
